#    ███████╗███████╗██████╗  █████╗  ██████╗██╗  ██╗██╗   ██╗██████╗ 
#   ╚════██║╚══███╔╝██╔══██╗██╔══██╗██╔════╝██║ ██╔╝██║   ██║██╔══██╗
#      ██╔╝  ███╔╝ ██████╔╝███████║██║     █████╔╝ ██║   ██║██████╔╝
#    ██╔╝  ███╔╝  ██╔══██╗██╔══██║██║     ██╔═██╗ ██║   ██║██╔═══╝ 
#   ██║  ███████╗██████╔╝██║  ██║╚██████╗██║  ██╗╚██████╔╝██║     
#   ╚═╝  ╚══════╝╚═════╝ ╚═╝  ╚═╝ ╚═════╝╚═╝  ╚═╝ ╚═════╝ ╚═╝     
# SevenZipBackup   -   by Windsor Macmillan

version: 4

# Backup interval in minutes.
# 备份间隔，单位分钟
delay: 60
# How many backups to keep before deleting the oldest one. Set this to -1 to disable automatic deletes.
# 保存上限，超过则清理最旧的备份。禁用此项请改为 -1
keep-count: -1
local-keep-count: -1

# The priority of the backup thread [1-10]. Lower value cause less server lag. Increase this value if backup takes too long.
# WARNING: High value may significantly increase server lag, typically accounting for 10-30 ms tick time.
# 备份线程的优先级[1-10]，更低值会减少服务器卡顿影响，若备份用时过长请酌情增加
# 警告：过高的值可能会显著增加服务器mspt，实测中影响能达到10~30。
backup-thread-priority: 5
# Compress level for 7zip archive [0-9]. 0 refers to super-fast. 9 refers to extreme-compression. Increasing this value can create smaller backup.
# Based on actual testing, we STRONGLY RECOMMEND level 5 or lower.
# WARNING: Beyond this value, compression rate would NOT improve significantly, while time and memory consumption increase exponentially.
# 7z压缩级别[0-9]，0代表最快速度，9代表极限压缩。提高此值可以获得更小体积的备份。
# 经过实测强烈建议选用5及以下，超过此值压缩率不会显著改善，但消耗时间和内存成倍增加。
# 警告：过高的值可能会消耗巨量内存和CPU资源。
7z-compression-level: 1
# Compressing thread counts. Each thread can process backups creation in parallel.
# Default is 4. Based on directories you need to create backups. (0 means keep same as CPU cores count)
# 压缩线程数量。每个线程可以并行地创建备份文件。
# 默认值为4。此值基于你需要创建备份的文件夹数量。(0表示与CPU核心数保持一致)
backup-thread-counts: 4
# This determines whether threads are assigned to specified CPU cores.
# 此项决定是否启用线程绑定到指定CPU核心
enable-specify-cpu-cores: true
# Specify CPU cores list to bind backup threads. (Separated by comma, -1 means automatic, will bind last several CPU cores)
# We suggest you to specify CPU cores to non-main-thread cores to avoid impacting performance of the server.
# 绑定压缩线程到特定CPU核心列表（逗号分隔，-1表示自动，会绑定到最后几个CPU核心）
# 建议绑定到非主线程的CPU核心以免影响服务器性能
# cpu-cores-list: "0,1,2,3"
# cpu-cores-list: "12,13,14,15"
cpu-cores-list: "-1"

#只在有玩家在线时启用备份
backups-require-players: true
#在备份时暂时挂起世界保存
disable-saving-during-backups: true
#备份时显示boos栏进度条
show-bossbar-progress: true
#You can choose from 7 colors: BLUE, GREEN, PINK, PURPLE, RED, WHITE and YELLOW
#可用7钟颜色：BLUE, GREEN, PINK, PURPLE, RED, WHITE and YELLOW
bossbar-color: "BLUE"
#You can choose from 5 styles: SOLID, SEGMENT_6, SEGMENT_10, SEGMENT_12, SEGMENT_20
#可用风格：SOLID, SEGMENT_6, SEGMENT_10, SEGMENT_12, SEGMENT_20
bossbar-style: "SOLID"


scheduled-backups: false
backup-schedule-list:

backup-list:
  # Backup all kinds of world
  # 备份所有世界文件夹
  - glob: "*world*"
    format: "Backup-%NAME-%FORMAT.zip"
    create: true
  # Backup plugins' data, but exclude jar files and cache
  # 备份插件数据，但不包含插件本体和缓存文件
  - path: "plugins"
    format: "Backup-plugins-%FORMAT.zip"
    create: true
    blacklist:
      - "*jar"
      - ".paper-remapped/**"
      - "*cache*"

external-backup-list:

local-save-directory: "backups"
remote-save-directory: "backups"

googledrive:
  enabled: false
  shared-drive-id: ""
onedrive:
  enabled: false
dropbox:
  enabled: false
webdav:
  enabled: false
  hostname: "http://example.com/directory"
  username: "Username"
  password: "Password"
nextcloud:
  enabled: false
  hostname: "https://example.com/remote.php/dav/files/user/"
  username: "Username"
  password: "Password"
  chunk-size: 20_000_000
s3:
  enabled: false
  endpoint: "https://s3.us-west-2.amazonaws.com"
  access-key: "AKIAxxxxxxxxxxxxxxxx"
  secret-key: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
  bucket: "bucket"
ftp:
  enabled: false
  hostname: "ftp.example.com"
  port: 21
  sftp: false
  ftps: false
  username: "Username"
  password: "Password"
  sftp-public-key: 
  sftp-passphrase: 
  working-dir:

messages:
  send-in-chat: true
  # prefix: "&6[&f7&8z&bBackup&6] "
  prefix: "&6[&f7&8z&b备份&6] "
  default-color: "&3"

advanced:
  metrics: true
  update-check: true
  suppress-errors: false
  debug: false
  date-language: "cn"
  # UTC
  date-timezone: "+08:00"
  ftp-file-separator: "/"
